CREATE DATABASE COMERCIO_STAGE
GO

USE COMERCIO_STAGE
GO
  
CREATE TABLE ST_CATEGORIA(
	IDCATEGORIA int NULL,
	NOME varchar(50) NULL
) 
GO

CREATE TABLE ST_CLIENTE(
  IDCLIENTE INT DEFAULT NULL,
  NOME VARCHAR(100) DEFAULT NULL,
  SEXO VARCHAR(20) DEFAULT NULL,
  NASCIMENTO DATE DEFAULT NULL,
  CIDADE VARCHAR(100) DEFAULT NULL,
  REGIAO VARCHAR(20) DEFAULT NULL
)
GO

CREATE TABLE ST_FATO(
	IDCLIENTE int NULL,
	IDVENDEDOR int NULL,
	IDPRODUTO int NULL,
	IDFORNECEDOR int NULL,
	IDNOTA int NULL,
	IDFORMA int NULL,
	QUANTIDADE int NULL,
	TOTAL_ITEM numeric(10, 2) NULL,
	DATA date NULL,
	CUSTO_TOTAL numeric(10, 2) NULL,
	LUCRO_TOTAL numeric(10, 2) NULL
) 
GO


CREATE TABLE ST_FORMA(
	IDFORMA int NULL,
	FORMA varchar(50) NULL
) 
GO

CREATE TABLE ST_FORNECEDOR(
	IDFORNECEDOR int NULL,
	NOME varchar(50) NULL
)
GO

CREATE TABLE ST_NOTA(
	IDNOTA int NULL
) 
GO

CREATE TABLE ST_PRODUTO(
	IDPRODUTO int NULL,
	NOME varchar(50) NULL,
	VALOR_UNITARIO numeric(10, 2) NULL,
	CUSTO_MEDIO numeric(10, 2) NULL,
	ID_CATEGORIA int NULL
) 
GO

CREATE TABLE ST_VENDEDOR(
	IDVENDEDOR int NULL,
	NOME varchar(50) NULL,
	SEXO varchar(20) NULL,
	IDGERENTE int NULL
) 
GO
